/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.*;

public class InsertAddresses extends javax.swing.JDialog {
    /**
     * Creates new form InsertAuthorDialog
     */
    private final HashMap ht;
    private final Database db;

    public InsertAddresses(java.awt.Frame parent, Database db) {
        super(parent, true);
        initComponents();
        this.db = db;
        this.setSize(450,450);
        this.setLayout(null);
        ht = new HashMap<String, Integer>();
        // Construir el combo con el ID y Nombre de proveedor
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        Address_ID = new JTextField();
        Line_1 = new JTextField();
        Line_2 = new JTextField();
        city = new JTextField();
        postcode = new JTextField();
        county_province_state = new JTextField();
        country = new JTextField();
        other_details = new JTextField();
        okButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Address");
        setResizable(false);

        jLabel1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Address ID:");
        jLabel1.setBounds(40,40,160,30);

        jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Line 1:");
        jLabel2.setBounds(40,80,160,30);

        jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Line 2:");
        jLabel3.setBounds(40,120,160,30);

        jLabel4.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("City:");
        jLabel4.setBounds(40,160,160,30);

        jLabel5.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Post Code:");
        jLabel5.setBounds(40,200,160,30);

        jLabel6.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("County/Province/State:");
        jLabel6.setBounds(40,240,160,30);

        jLabel7.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Country:");
        jLabel7.setBounds(40,280,160,30);

        jLabel8.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Other details:");
        jLabel8.setBounds(40,320,160,30);

        //txtId.setColumns(42);
        Address_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Address_ID.setBounds(200,40,200,30);
        Address_ID.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        //listed_building_yn.setColumns(11);
        Line_1.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Line_1.setBounds(200,80,200,30);
        //shop_yn.setColumns(11);
        Line_2.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Line_2.setBounds(200,120,200,30);
        //smoking_yn.setColumns(11);
        city.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        city.setBounds(200,160,200,30);
        //admission_charge.setColumns(11);
        postcode.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        postcode.setBounds(200,200,200,30);

        county_province_state.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        county_province_state.setBounds(200,240,200,30);

        country.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        country.setBounds(200,280,200,30);

        other_details.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        other_details.setBounds(200,320,200,30);

        okButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Add");
        okButton.setBounds(120, 365, 100, 30);
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBounds(250, 365, 100, 30);
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        add(jLabel1);
        add(Address_ID);
        add(jLabel2);
        add(Line_1);
        add(jLabel3);
        add(Line_2);
        add(jLabel4);
        add(city);
        add(jLabel5);
        add(postcode);
        add(jLabel6);
        add(county_province_state);
        add(jLabel7);
        add(country);
        add(jLabel8);
        add(other_details);
        add(okButton);
        add(cancelButton);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer addressid = Integer.parseInt(Address_ID.getText());
        System.out.println("Address ID = " + addressid);
        String line1 = Line_1.getText();
        System.out.println("Line 1 = " + line1);
        String line2 = Line_2.getText();
        System.out.println("Line 2 = " + line2);
        String citytxt = city.getText();
        System.out.println("City = " + citytxt);
        String postal = postcode.getText();
        System.out.println("Post code = " + postal);
        String county = county_province_state.getText();
        System.out.println("County/province/state = " + county);
        String countrytxt = country.getText();
        System.out.println("Country = " + countrytxt);
        String other = other_details.getText();
        System.out.println("Other details = " + other);

        StringBuilder sql
                = new StringBuilder("INSERT INTO \"Addresses\" VALUES (");
        sql.append(addressid);
        sql.append(",\'");
        sql.append(line1);
        sql.append("\',\'");
        sql.append(line2);
        sql.append("\',\'");
        sql.append(citytxt);
        sql.append("\',\'");
        sql.append(postal);
        sql.append("\',\'");
        sql.append(county);
        sql.append("\',\'");
        sql.append(countrytxt);
        sql.append("\',\'");
        sql.append(other);
        sql.append("\')");

        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting the address data.");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String text = Address_ID.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce the Address ID");
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField Address_ID;
    private javax.swing.JTextField Line_1;
    private javax.swing.JTextField Line_2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField postcode;
    private javax.swing.JTextField county_province_state;
    private javax.swing.JTextField country;
    private javax.swing.JTextField other_details;
    // End of variables declaration//GEN-END:variables
}