/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.*;

public class InsertArtefacts extends javax.swing.JDialog {
    /**
     * Creates new form InsertAuthorDialog
     */
    private final HashMap ht;
    private final Database db;

    public InsertArtefacts(java.awt.Frame parent, Database db) {
        super(parent, true);
        initComponents();
        this.db = db;
        this.setSize(450,450);
        this.setLayout(null);
        ht = new HashMap<String, Integer>();
        // Construir el combo con el ID y Nombre de proveedor
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        Artefact_ID = new JTextField();
        Date_aquired = new JTextField();
        Date_Disposed_Of = new JTextField();
        Artefact_Name = new JTextField();
        Artefact_Description = new JTextField();
        Other_Details = new JTextField();
        Museum_ID = new JTextField();
        Period_Code = new JTextField();
        okButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Artefacts");
        setResizable(false);

        jLabel1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Artefact ID:");
        jLabel1.setBounds(40,40,160,30);

        jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date Aquired:");
        jLabel2.setBounds(40,80,160,30);

        jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date disposed of:");
        jLabel3.setBounds(40,120,160,30);

        jLabel4.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Artefact name:");
        jLabel4.setBounds(40,160,160,30);

        jLabel5.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Artefact description:");
        jLabel5.setBounds(40,200,160,30);

        jLabel6.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Other details:");
        jLabel6.setBounds(40,240,160,30);

        jLabel7.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Museum ID:");
        jLabel7.setBounds(40,280,160,30);

        jLabel8.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Period code:");
        jLabel8.setBounds(40,320,160,30);

        //txtId.setColumns(42);
        Artefact_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Artefact_ID.setBounds(200,40,200,30);
        Artefact_ID.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        //listed_building_yn.setColumns(11);
        Date_aquired.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Date_aquired.setBounds(200,80,200,30);
        //shop_yn.setColumns(11);
        Date_Disposed_Of.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Date_Disposed_Of.setBounds(200,120,200,30);
        //smoking_yn.setColumns(11);
        Artefact_Name.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Artefact_Name.setBounds(200,160,200,30);
        //admission_charge.setColumns(11);
        Artefact_Description.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Artefact_Description.setBounds(200,200,200,30);

        Other_Details.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Other_Details.setBounds(200,240,200,30);

        Museum_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Museum_ID.setBounds(200,280,200,30);

        Period_Code.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Period_Code.setBounds(200,320,200,30);

        okButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Add");
        okButton.setBounds(120, 360, 100, 30);
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBounds(250, 360, 100, 30);
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        add(jLabel1);
        add(Artefact_ID);
        add(jLabel2);
        add(Date_aquired);
        add(jLabel3);
        add(Date_Disposed_Of);
        add(jLabel4);
        add(Artefact_Name);
        add(jLabel5);
        add(Artefact_Description);
        add(jLabel6);
        add(Other_Details);
        add(jLabel7);
        add(Museum_ID);
        add(jLabel8);
        add(Period_Code);
        add(okButton);
        add(cancelButton);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer artefactid = Integer.parseInt(Artefact_ID.getText());
        System.out.println("Artefact ID = " + artefactid);
        String date_aquiredText = Date_aquired.getText();
        System.out.println("Date aquired = " + date_aquiredText);
        String date_disposed = Date_Disposed_Of.getText();
        System.out.println("Date disposed of= " + date_disposed);
        String artefactname = Artefact_Name.getText();
        System.out.println("Artefact name = " + artefactname);
        String artefact_desc = Artefact_Description.getText();
        System.out.println("Artefact description = " + artefact_desc);
        String other = Other_Details.getText();
        System.out.println("Other details = " + other);
        String museum = Museum_ID.getText();
        System.out.println("Museum ID = " + museum);
        String period = Period_Code.getText();
        System.out.println("Period Code = " + period);

        StringBuilder sql
                = new StringBuilder("INSERT INTO \"Artefacts\"  VALUES (");
        sql.append(artefactid);
        sql.append(",\'");
        sql.append(date_aquiredText);
        sql.append("\',\'");
        sql.append(date_disposed);
        sql.append("\',\'");
        sql.append(artefactname);
        sql.append("\',\'");
        sql.append(artefact_desc);
        sql.append("\',\'");
        sql.append(other);
        sql.append("\',");
        sql.append(museum);
        sql.append(",");
        sql.append(period);
        sql.append(");");

        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting the Artefact data.");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String text = Artefact_ID.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce the Artefact ID");
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField Artefact_ID;
    private javax.swing.JTextField Date_aquired;
    private javax.swing.JTextField Date_Disposed_Of;
    private javax.swing.JTextField Artefact_Name;
    private javax.swing.JTextField Artefact_Description;
    private javax.swing.JTextField Other_Details;
    private javax.swing.JTextField Museum_ID;
    private javax.swing.JTextField Period_Code;
    // End of variables declaration//GEN-END:variables
}