/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.*;

public class InsertEvents extends javax.swing.JDialog {
    /**
     * Creates new form InsertAuthorDialog
     */
    private final HashMap ht;
    private final Database db;

    public InsertEvents(java.awt.Frame parent, Database db) {
        super(parent, true);
        initComponents();
        this.db = db;
        this.setSize(450,400);
        this.setLayout(null);
        ht = new HashMap<String, Integer>();
        // Construir el combo con el ID y Nombre de proveedor
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        Event_ID = new JTextField();
        Date_Start = new JTextField();
        Date_End = new JTextField();
        Event_Name = new JTextField();
        Event_Description = new JTextField();
        Museum_ID = new JTextField();
        okButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Artefacts");
        setResizable(false);

        jLabel1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Event ID:");
        jLabel1.setBounds(40,40,160,30);

        jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date start:");
        jLabel2.setBounds(40,80,160,30);

        jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date end:");
        jLabel3.setBounds(40,120,160,30);

        jLabel4.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Event name:");
        jLabel4.setBounds(40,160,160,30);

        jLabel5.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Event description:");
        jLabel5.setBounds(40,200,160,30);

        jLabel6.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Museum ID:");
        jLabel6.setBounds(40,240,160,30);

        //txtId.setColumns(42);
        Event_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Event_ID.setBounds(200,40,200,30);
        Event_ID.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        //listed_building_yn.setColumns(11);
        Date_Start.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Date_Start.setBounds(200,80,200,30);
        //shop_yn.setColumns(11);
        Date_End.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Date_End.setBounds(200,120,200,30);
        //smoking_yn.setColumns(11);
        Event_Name.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Event_Name.setBounds(200,160,200,30);
        //admission_charge.setColumns(11);
        Event_Description.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Event_Description.setBounds(200,200,200,30);


        Museum_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        Museum_ID.setBounds(200,240,200,30);

        okButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Add");
        okButton.setBounds(120, 280, 100, 30);
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBounds(250, 280, 100, 30);
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        add(jLabel1);
        add(Event_ID);
        add(jLabel2);
        add(Date_Start);
        add(jLabel3);
        add(Date_End);
        add(jLabel4);
        add(Event_Name);
        add(jLabel5);
        add(Event_Description);
        add(jLabel6);
        add(Museum_ID);
        add(okButton);
        add(cancelButton);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer eventid = Integer.parseInt(Event_ID.getText());
        System.out.println("Event ID = " + eventid);
        String start = Date_Start.getText();
        System.out.println("Date start = " + start);
        String end = Date_End.getText();
        System.out.println("Date end= " + end);
        String eventname = Event_Name.getText();
        System.out.println("Event name = " + eventname);
        String event_desc = Event_Description.getText();
        System.out.println("Event description = " + event_desc);
        String museum_idText = Museum_ID.getText();
        System.out.println("Museum ID = " + museum_idText);

        StringBuilder sql
                = new StringBuilder("INSERT INTO \"Events\" VALUES (");
        sql.append(eventid);
        sql.append(",\'");
        sql.append(start);
        sql.append("\',\'");
        sql.append(end);
        sql.append("\',\'");
        sql.append(eventname);
        sql.append("\',\'");
        sql.append(event_desc);
        sql.append("\',");
        sql.append(museum_idText);
        sql.append(")");


        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting the event data.");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String text = Event_ID.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce the Event ID");
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField Event_ID;
    private javax.swing.JTextField Date_Start;
    private javax.swing.JTextField Date_End;
    private javax.swing.JTextField Event_Name;
    private javax.swing.JTextField Event_Description;
    private javax.swing.JTextField Museum_ID;
    // End of variables declaration//GEN-END:variables
}