/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.*;

public class InsertMuseumDialog extends javax.swing.JDialog {
    /**
     * Creates new form InsertAuthorDialog
     */
    private final HashMap ht;
    private final Database db;

    public InsertMuseumDialog(java.awt.Frame parent, Database db) {
        super(parent, true);
        initComponents();
        this.db = db;
        this.setSize(450,600);
        this.setLayout(null);
        ht = new HashMap<String, Integer>();
        // Construir el combo con el ID y Nombre de proveedor
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        museum_ID = new JTextField();
        listed_building_yn = new JTextField();
        shop_yn = new JTextField();
        smoking_yn = new JTextField();
        admission_charge = new JTextField();
        anual_visitor_count = new JTextField();
        date_built = new JTextField();
        date_became_museum = new JTextField();
        opening_hours = new JTextField();
        museum_name = new JTextField();
        other_museum_details = new JTextField();
        okButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Museum");
        setResizable(false);

        jLabel1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Museum ID:");
        jLabel1.setBounds(40,40,160,30);

        jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Listed Building:");
        jLabel2.setBounds(40,80,160,30);

        jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Shop:");
        jLabel3.setBounds(40,120,160,30);

        jLabel4.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Smoking:");
        jLabel4.setBounds(40,160,160,30);

        jLabel5.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Admission charge :");
        jLabel5.setBounds(40,200,160,30);

        jLabel6.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Anual Vistor Count:");
        jLabel6.setBounds(40,240,160,30);

        jLabel7.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date built:");
        jLabel7.setBounds(40,280,160,30);

        jLabel8.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date became museum:");
        jLabel8.setBounds(40,320,160,30);

        jLabel9.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Opening Hours:");
        jLabel9.setBounds(40,360,160,30);

        jLabel10.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Museum name:");
        jLabel10.setBounds(40,400,160,30);

        jLabel11.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Other museum details:");
        jLabel11.setBounds(40,440,160,30);

        //txtId.setColumns(42);
        museum_ID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        museum_ID.setBounds(200,40,200,30);
        museum_ID.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        //listed_building_yn.setColumns(11);
        listed_building_yn.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        listed_building_yn.setBounds(200,80,200,30);
        //shop_yn.setColumns(11);
        shop_yn.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        shop_yn.setBounds(200,120,200,30);
        //smoking_yn.setColumns(11);
        smoking_yn.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        smoking_yn.setBounds(200,160,200,30);
        //admission_charge.setColumns(11);
        admission_charge.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        admission_charge.setBounds(200,200,200,30);

        anual_visitor_count.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        anual_visitor_count.setBounds(200,240,200,30);

        date_built.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        date_built.setBounds(200,280,200,30);

        date_became_museum.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        date_became_museum.setBounds(200,320,200,30);

        opening_hours.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        opening_hours.setBounds(200,360,200,30);

        museum_name.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        museum_name.setBounds(200,400,200,30);

        other_museum_details.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        other_museum_details.setBounds(200,440,200,30);

        okButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Add");
        okButton.setBounds(120, 490, 100, 30);
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBounds(250, 490, 100, 30);
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        add(jLabel1);
        add(museum_ID);
        add(jLabel2);
        add(listed_building_yn);
        add(jLabel3);
        add(shop_yn);
        add(jLabel4);
        add(smoking_yn);
        add(jLabel5);
        add(admission_charge);
        add(jLabel6);
        add(anual_visitor_count);
        add(jLabel7);
        add(date_built);
        add(jLabel8);
        add(date_became_museum);
        add(jLabel9);
        add(opening_hours);
        add(jLabel10);
        add(museum_name);
        add(jLabel11);
        add(other_museum_details);
        add(okButton);
        add(cancelButton);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer museumid = Integer.parseInt(museum_ID.getText());
        System.out.println("Museum ID = " + museumid);
        String listed = listed_building_yn.getText();
        System.out.println("Listed building = " + listed);
        String shop = shop_yn.getText();
        System.out.println("Shop = " + shop);
        String smoking = smoking_yn.getText();
        System.out.println("Smoking = " + smoking);
        String admission = admission_charge.getText();
        System.out.println("Admission Charge = " + admission);
        String anual_visitor = anual_visitor_count.getText();
        System.out.println("Anual Visitor Count = " + anual_visitor);
        String datebuilt = date_built.getText();
        System.out.println("Date Built = " + datebuilt);
        String datemuseum = date_became_museum.getText();
        System.out.println("Date became museum = " + datemuseum);
        String opening = opening_hours.getText();
        System.out.println("Opening Hours = " + opening);
        String museumname = museum_name.getText();
        System.out.println("Museum Name  = " + museumname);
        String other = other_museum_details.getText();
        System.out.println("Other museum details = " + other);

        StringBuilder sql
                //= new StringBuilder("INSERT INTO \"Museum\" (museum_ID,listed_building_yn,shop_yn,smoking_yn,admission_charge,anual_visitor_count,date_built,opening_hours,museum_name,other_museum_details) VALUES (");
                = new StringBuilder("INSERT INTO \"Museum\" VALUES (");
        sql.append(museumid);
        sql.append(",\'");
        sql.append(listed);
        sql.append("\',\'");
        sql.append(shop);
        sql.append("\',\'");
        sql.append(smoking);
        sql.append("\',\'");
        sql.append(admission);
        sql.append("\',");
        sql.append(anual_visitor);
        sql.append(",\'");
        sql.append(datebuilt);
        sql.append("\',\'");
        sql.append(datemuseum);
        sql.append("\',\'");
        sql.append(opening);
        sql.append("\',\'");
        sql.append(museumname);
        sql.append("\',\'");
        sql.append(other);
        sql.append("\');");

        System.out.println( sql.toString() );

        try {
            db.update( sql.toString() );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting the museum data.");
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String text = museum_ID.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce the museum ID");
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField museum_ID;
    private javax.swing.JTextField listed_building_yn;
    private javax.swing.JTextField shop_yn;
    private javax.swing.JTextField smoking_yn;
    private javax.swing.JTextField admission_charge;
    private javax.swing.JTextField anual_visitor_count;
    private javax.swing.JTextField date_built;
    private javax.swing.JTextField date_became_museum;
    private javax.swing.JTextField opening_hours;
    private javax.swing.JTextField museum_name;
    private javax.swing.JTextField other_museum_details;
    // End of variables declaration//GEN-END:variables
}

